
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/my-spring-security?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
